[package]
name = "rust-virtio-drivers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
virtio-drivers="0.7.1"
volatile = "0.3.0"
log = "0.4"
